tap 'caskroom/cask'
cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'autojump'
brew 'bash'
brew 'ccat'
brew 'cctools'
brew 'coreutils'
brew 'curl'
brew 'diff-so-fancy'
brew 'direnv'
brew 'fd'
brew 'ffmpeg'
brew 'findutils'
brew 'fpp'
brew 'gdb'
brew 'gifsicle'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnupg'
brew 'graphicsmagick'
brew 'grc'
brew 'grep', args: ['with-default-names']
brew 'htop-osx'
brew 'hub'
brew 'imagemagick'
brew 'kubectx'
brew 'libav'
brew 'libksba'
brew 'libyaml'
brew 'neovim'
brew 'nmap'
brew 'nvm'
brew 'openssl'
brew 'ossp-uuid'
brew 'postgresql'
brew 'pstree'
brew 'qt'
brew 'redis'
brew 'ripgrep'
brew 'roundup'
brew 'stern'
brew 'subliminal'
brew 'the_silver_searcher'
brew 'tig'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'webkit2png'
brew 'youtube-dl'

cask 'firefox'
cask 'google-chrome'
cask 'vlc'
